###
GET http://localhost:3000/tasks
content-type: application/json

{
    "authorization": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.S1Cg_Ilvjkhb5e0YIUFwWvhtIeqkdjhmDx9IBKMf5qg"
}

###
GET http://localhost:3000

###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "Compras"
}

###
PUT http://localhost:3000/tasks/5 HTTP/1.1
content-type: application/json

{
    "title": "Fazer Compras"
}

###
DELETE http://localhost:3000/tasks/5 HTTP/1.1

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "User 3",
    "email": "user3@email.com"
}

###
DELETE http://localhost:3000/users/3 HTTP/1.1

###
POST http://localhost:3000/token HTTP/1.1
content-type: application/json

{
    "email": "admin@mail.net",
    "password": "12345"
}